This is labeled "start reporter", but this turned into a test refactor.
jgstr/twitchwebsub pull request #18
Opened 2020-09-09 23:56 UTC by jgstr

Currently, the request is for:

1. Review that the [subscriber test ](https://github.com/jgstr/twitchwebsub/blob/4066fab7e543449f3df2fdc332a7fee0ad91c850/tests/subscriber-tests.js#L21)is testing as it should, and...
2. That the refactor for [subscriber.saveEvent](https://github.com/jgstr/twitchwebsub/blob/4066fab7e543449f3df2fdc332a7fee0ad91c850/subscriber/subscriber.js#L26) is good.

Questions:
1. Should saveEvent use some kind of asynchronous feature? Allowing the loop to continue only after the dataStore.saveEvent completes? 
2. Should saveEvent in the subscriber or data-store handle these queries differently? To reduce calls to the database?

2020-09-10 06:36 UTC, nargov reviewed
Will continue later, but there's already a lot of work to be done.

2020-09-10 06:36 UTC, nargov commented on utils/test-utils-ORIGINAL.js
> +const path = require("path");
Is this file still needed?

2020-09-10 06:36 UTC, nargov commented on end-to-end/subscriber-driver.js
> +      `http://localhost:3000/get-subscription/${subscriptionID}`
extract `http://localhost:3000` to a constant or something

2020-09-10 06:36 UTC, nargov commented on end-to-end/subscriber-driver.js
> +      params: {
Leaky abstraction. The API users don't need to know about things like `topic`, `to_id`, `from_id` and the like.
Think about what you would like to be able to write as a user of this system.

2020-09-10 06:36 UTC, nargov commented on end-to-end/subscriber-driver.js
> +        "Client-ID": subscription.clientID,
Isn't client ID internal to the application itself?

2020-09-10 06:36 UTC, nargov commented on end-to-end/subscriber-driver.js
> +              console.log("* Database up.");
If what you're checking is that the server is responding, why do you print `Database up`?

2020-09-10 06:36 UTC, nargov commented on end-to-end/subscriber-driver.js
> +              setTimeout(pollStatus, 3000);
What happens if the server is never up?

2020-09-10 06:36 UTC, nargov commented on end-to-end/e2e-test.js
> +  it("should report a getAllSubscriptions request.", function (done) {
This shouldn't be an e2e.

2020-09-10 06:36 UTC, nargov commented on subscriber/doubles/data-store-fake.js
> +        (event) => ({
This conversion shouldn't be needed.
If the event format isn't great coming from twitch, change it _before_ saving it to the database, and not on every read.

2020-09-10 06:36 UTC, nargov commented on subscriber/doubles/data-store-fake.js
> +        (event) => ({
Same as above

2020-09-10 06:38 UTC, nargov commented
Saving events in a loop might not be a great idea if you get a lot of events.
What you can do is batch the inserts. 
`INSERT INTO tbl_name (a,b,c) VALUES(1,2,3),(4,5,6),(7,8,9);`

2020-09-10 06:39 UTC, nargov commented
https://stackoverflow.com/questions/8899802/how-do-i-do-a-bulk-insert-in-mysql-using-node-js

2020-09-11 23:52 UTC, jgstr commented on end-to-end/subscriber-driver.js
> +        "Client-ID": subscription.clientID,
I moved the client ID and OAuth tokens to the (gitignored) authentications file. The twitched adapter (twitch.js) then takes these values as parameters. I "wired" them to twitch.js because, the way I justified it, these are in the Twitch API domain. Twitch dictates these values, so they should be as close to the twitch adapter as possible, without also being security risks.

2020-09-11 23:53 UTC, jgstr commented on end-to-end/subscriber-driver.js
> +              console.log("* Database up.");
Removed the log.

2020-09-12 00:03 UTC, jgstr commented on end-to-end/subscriber-driver.js
> +              setTimeout(pollStatus, 3000);
I added a `connectionAttempts` counter to `pollStatus`. Rejects promise after 8 attempts. The amount is arbitrary, but any attempts after 8 should be examined anyway.

2020-09-12 00:06 UTC, jgstr commented on end-to-end/e2e-test.js
> +  it("should report a getAllSubscriptions request.", function (done) {
I removed this test.

2020-09-12 13:04 UTC, nargov commented on end-to-end/subscriber-driver.js
> +              setTimeout(pollStatus, 3000);
I don't see it anywhere, did you not commit the change?

2020-09-12 17:14 UTC, jgstr commented on end-to-end/subscriber-driver.js
> +              setTimeout(pollStatus, 3000);
I think I forgot to push, so I just did now. But now all of the files read "Outdated" next to it. I think you'll see the change in the latest push in this branch, but not here.

2020-09-16 18:00 UTC, jgstr commented on subscriber/doubles/data-store-fake.js
> +        (event) => ({
This function is now very simple. I applied what I learned from Robert Martin's TPP article. Once a new test requires more code, I will then write more robust code.

2020-09-18 17:10 UTC, nargov commented on subscriber/adapters/data-store.js
> +      const parseMessageToJSON = (results) => results.map(result => {
`map` implies immutability.
However, you're changing the original object.

2020-09-18 17:14 UTC, nargov requested changes

2020-09-18 17:14 UTC, nargov commented on subscriber/adapters/data-store.js
> +      const stringifyEvents = event => {
The name of the function is misleading

2020-09-18 17:14 UTC, nargov commented on subscriber/adapters/web.js
> +    subscriberManager.saveEvent(subID, eventData);
Didn't we say that `request.body.data` might contain multiple events?

2020-10-17 17:00 UTC, merged